---
name: Test
on:
  push:
    branches:
      - "*"
      - "!releases/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - run: go test -cover ./...
        env:
          CGO_ENABLED: 0

# enable staticcheck when we reach maturity
#      - name: Staticcheck
#        run: |
#          go get -u honnef.co/go/tools/cmd/staticcheck
#          staticcheck ./...
